# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ui_files/customDrink.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomDrinkWidget(object):
    def setupUi(self, CustomDrinkWidget):
        CustomDrinkWidget.setObjectName("CustomDrinkWidget")
        CustomDrinkWidget.resize(642, 352)
        CustomDrinkWidget.setStyleSheet("QLabel{\n"
"color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"color: rgb(255,255,255);\n"
"}\n"
"\n"
"QProgressBar{\n"
"color: rgb(255,255,255);\n"
"}")
        self.drinkOptionsGroupBox = QtWidgets.QGroupBox(CustomDrinkWidget)
        self.drinkOptionsGroupBox.setGeometry(QtCore.QRect(20, 20, 611, 141))
        self.drinkOptionsGroupBox.setStyleSheet("QGroupBox{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox:indicator:unchecked{\n"
"image: url(:/images/images/checkbox-unchecked.svg);\n"
"}\n"
"\n"
"QCheckBox:indicator:checked{\n"
"image: url(:/images/images/checkbox-checked.svg);\n"
"}")
        self.drinkOptionsGroupBox.setCheckable(False)
        self.drinkOptionsGroupBox.setChecked(False)
        self.drinkOptionsGroupBox.setObjectName("drinkOptionsGroupBox")
        self.customDrinkHelpLabel = QtWidgets.QLabel(self.drinkOptionsGroupBox)
        self.customDrinkHelpLabel.setGeometry(QtCore.QRect(70, 110, 441, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.customDrinkHelpLabel.setFont(font)
        self.customDrinkHelpLabel.setObjectName("customDrinkHelpLabel")
        self.drinkOption1 = QtWidgets.QCheckBox(self.drinkOptionsGroupBox)
        self.drinkOption1.setEnabled(True)
        self.drinkOption1.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.drinkOption1.setFont(font)
        self.drinkOption1.setObjectName("drinkOption1")
        self.drinkOption2 = QtWidgets.QCheckBox(self.drinkOptionsGroupBox)
        self.drinkOption2.setEnabled(True)
        self.drinkOption2.setGeometry(QtCore.QRect(20, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.drinkOption2.setFont(font)
        self.drinkOption2.setObjectName("drinkOption2")
        self.drinkOption3 = QtWidgets.QCheckBox(self.drinkOptionsGroupBox)
        self.drinkOption3.setEnabled(True)
        self.drinkOption3.setGeometry(QtCore.QRect(220, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.drinkOption3.setFont(font)
        self.drinkOption3.setObjectName("drinkOption3")
        self.drinkOption4 = QtWidgets.QCheckBox(self.drinkOptionsGroupBox)
        self.drinkOption4.setEnabled(True)
        self.drinkOption4.setGeometry(QtCore.QRect(220, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.drinkOption4.setFont(font)
        self.drinkOption4.setObjectName("drinkOption4")
        self.drinkOption5 = QtWidgets.QCheckBox(self.drinkOptionsGroupBox)
        self.drinkOption5.setEnabled(True)
        self.drinkOption5.setGeometry(QtCore.QRect(430, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.drinkOption5.setFont(font)
        self.drinkOption5.setObjectName("drinkOption5")
        self.drinkOption6 = QtWidgets.QCheckBox(self.drinkOptionsGroupBox)
        self.drinkOption6.setEnabled(True)
        self.drinkOption6.setGeometry(QtCore.QRect(430, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.drinkOption6.setFont(font)
        self.drinkOption6.setObjectName("drinkOption6")
        self.saveCustomDrinkButton = QtWidgets.QPushButton(CustomDrinkWidget)
        self.saveCustomDrinkButton.setGeometry(QtCore.QRect(40, 270, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.saveCustomDrinkButton.setFont(font)
        self.saveCustomDrinkButton.setStyleSheet("QPushButton {\n"
"background-color: none;\n"
"    background-image: url(:/images/images/save.svg);\n"
"    border: solid;\n"
"    max-width:50px;\n"
"  max-height:50px;\n"
"  min-width:50px;\n"
"  min-height:50px;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0, stop: 1\n"
"        );\n"
"    }")
        self.saveCustomDrinkButton.setText("")
        self.saveCustomDrinkButton.setObjectName("saveCustomDrinkButton")
        self.clearCustomDrinkButton = QtWidgets.QPushButton(CustomDrinkWidget)
        self.clearCustomDrinkButton.setGeometry(QtCore.QRect(290, 270, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.clearCustomDrinkButton.setFont(font)
        self.clearCustomDrinkButton.setStyleSheet("QPushButton {\n"
"background-image: url(:/images/images/clear.svg);\n"
"background-color: none;\n"
"    border-radius: 23px;\n"
"    max-width:50px;\n"
"  max-height:50px;\n"
"  min-width:50px;\n"
"  min-height:50px;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0, stop: 1\n"
"        );\n"
"    }")
        self.clearCustomDrinkButton.setText("")
        self.clearCustomDrinkButton.setObjectName("clearCustomDrinkButton")
        self.makeCustomDrinkButton = QtWidgets.QPushButton(CustomDrinkWidget)
        self.makeCustomDrinkButton.setGeometry(QtCore.QRect(520, 270, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.makeCustomDrinkButton.setFont(font)
        self.makeCustomDrinkButton.setStyleSheet("QPushButton {\n"
"background-image: url(:/images/images/mixit-icon.svg);\n"
"background-color: none;\n"
"    border: solid;\n"
"    border-radius: 23px;\n"
"    max-width:50px;\n"
"  max-height:50px;\n"
"  min-width:50px;\n"
"  min-height:50px;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0, stop: 1\n"
"        );\n"
"    }")
        self.makeCustomDrinkButton.setText("")
        self.makeCustomDrinkButton.setObjectName("makeCustomDrinkButton")
        self.customDrinkProgressBar = QtWidgets.QProgressBar(CustomDrinkWidget)
        self.customDrinkProgressBar.setEnabled(True)
        self.customDrinkProgressBar.setGeometry(QtCore.QRect(20, 300, 611, 23))
        self.customDrinkProgressBar.setProperty("value", 24)
        self.customDrinkProgressBar.setObjectName("customDrinkProgressBar")
        self.mixItLabel = QtWidgets.QLabel(CustomDrinkWidget)
        self.mixItLabel.setEnabled(True)
        self.mixItLabel.setGeometry(QtCore.QRect(510, 330, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.mixItLabel.setFont(font)
        self.mixItLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mixItLabel.setObjectName("mixItLabel")
        self.clearLabel = QtWidgets.QLabel(CustomDrinkWidget)
        self.clearLabel.setEnabled(True)
        self.clearLabel.setGeometry(QtCore.QRect(280, 330, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.clearLabel.setFont(font)
        self.clearLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.clearLabel.setObjectName("clearLabel")
        self.saveLabel = QtWidgets.QLabel(CustomDrinkWidget)
        self.saveLabel.setEnabled(True)
        self.saveLabel.setGeometry(QtCore.QRect(30, 330, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.saveLabel.setFont(font)
        self.saveLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saveLabel.setObjectName("saveLabel")
        self.strengthLevelGroupBox = QtWidgets.QGroupBox(CustomDrinkWidget)
        self.strengthLevelGroupBox.setGeometry(QtCore.QRect(20, 170, 611, 91))
        self.strengthLevelGroupBox.setAutoFillBackground(False)
        self.strengthLevelGroupBox.setStyleSheet("QGroupBox{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton{\n"
"font: italic 10pt \"Century Schoolbook\";\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QRadioButton:indicator:unchecked{\n"
"image: url(:/images/images/radio-unchecked.svg);\n"
"}\n"
"\n"
"QRadioButton:indicator:checked{\n"
"image: url(:/images/images/radio-checked.svg);\n"
"}")
        self.strengthLevelGroupBox.setCheckable(False)
        self.strengthLevelGroupBox.setChecked(False)
        self.strengthLevelGroupBox.setObjectName("strengthLevelGroupBox")
        self.fiftyFiftyStrengthLevel = QtWidgets.QRadioButton(self.strengthLevelGroupBox)
        self.fiftyFiftyStrengthLevel.setEnabled(True)
        self.fiftyFiftyStrengthLevel.setGeometry(QtCore.QRect(150, 40, 82, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.fiftyFiftyStrengthLevel.setFont(font)
        self.fiftyFiftyStrengthLevel.setStyleSheet("")
        self.fiftyFiftyStrengthLevel.setObjectName("fiftyFiftyStrengthLevel")
        self.easyTigerStrengthLevel = QtWidgets.QRadioButton(self.strengthLevelGroupBox)
        self.easyTigerStrengthLevel.setEnabled(True)
        self.easyTigerStrengthLevel.setGeometry(QtCore.QRect(20, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.easyTigerStrengthLevel.setFont(font)
        self.easyTigerStrengthLevel.setStyleSheet("")
        self.easyTigerStrengthLevel.setObjectName("easyTigerStrengthLevel")
        self.littyTittyStrengthLevel = QtWidgets.QRadioButton(self.strengthLevelGroupBox)
        self.littyTittyStrengthLevel.setEnabled(True)
        self.littyTittyStrengthLevel.setGeometry(QtCore.QRect(270, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.littyTittyStrengthLevel.setFont(font)
        self.littyTittyStrengthLevel.setStyleSheet("")
        self.littyTittyStrengthLevel.setObjectName("littyTittyStrengthLevel")
        self.adioMfStrengthLevel = QtWidgets.QRadioButton(self.strengthLevelGroupBox)
        self.adioMfStrengthLevel.setEnabled(True)
        self.adioMfStrengthLevel.setGeometry(QtCore.QRect(410, 40, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.adioMfStrengthLevel.setFont(font)
        self.adioMfStrengthLevel.setStyleSheet("")
        self.adioMfStrengthLevel.setObjectName("adioMfStrengthLevel")
        self.customDrinkProgressBar.raise_()
        self.drinkOptionsGroupBox.raise_()
        self.saveCustomDrinkButton.raise_()
        self.clearCustomDrinkButton.raise_()
        self.makeCustomDrinkButton.raise_()
        self.mixItLabel.raise_()
        self.clearLabel.raise_()
        self.saveLabel.raise_()
        self.strengthLevelGroupBox.raise_()

        self.retranslateUi(CustomDrinkWidget)
        QtCore.QMetaObject.connectSlotsByName(CustomDrinkWidget)

    def retranslateUi(self, CustomDrinkWidget):
        _translate = QtCore.QCoreApplication.translate
        CustomDrinkWidget.setWindowTitle(_translate("CustomDrinkWidget", "Custom Drink"))
        self.drinkOptionsGroupBox.setTitle(_translate("CustomDrinkWidget", "Drink Options"))
        self.customDrinkHelpLabel.setText(_translate("CustomDrinkWidget", "To update drink options: Go to settings and update the pump configuration."))
        self.drinkOption1.setText(_translate("CustomDrinkWidget", "CheckBox"))
        self.drinkOption2.setText(_translate("CustomDrinkWidget", "CheckBox"))
        self.drinkOption3.setText(_translate("CustomDrinkWidget", "CheckBox"))
        self.drinkOption4.setText(_translate("CustomDrinkWidget", "CheckBox"))
        self.drinkOption5.setText(_translate("CustomDrinkWidget", "CheckBox"))
        self.drinkOption6.setText(_translate("CustomDrinkWidget", "CheckBox"))
        self.mixItLabel.setText(_translate("CustomDrinkWidget", "Mix It!"))
        self.clearLabel.setText(_translate("CustomDrinkWidget", "Clear"))
        self.saveLabel.setText(_translate("CustomDrinkWidget", "Save"))
        self.strengthLevelGroupBox.setTitle(_translate("CustomDrinkWidget", "Strength Level"))
        self.fiftyFiftyStrengthLevel.setText(_translate("CustomDrinkWidget", "50/50"))
        self.easyTigerStrengthLevel.setText(_translate("CustomDrinkWidget", "Easy Tiger"))
        self.littyTittyStrengthLevel.setText(_translate("CustomDrinkWidget", "Litty Titty"))
        self.adioMfStrengthLevel.setText(_translate("CustomDrinkWidget", "ADIOS MUTHAFUCKA!"))
from . import customDrinkWidgetResource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomDrinkWidget = QtWidgets.QWidget()
    ui = Ui_CustomDrinkWidget()
    ui.setupUi(CustomDrinkWidget)
    CustomDrinkWidget.show()
    sys.exit(app.exec_())
