# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ui_files/premadeDrinks.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PremadeDrinksWidget(object):
    def setupUi(self, PremadeDrinksWidget):
        PremadeDrinksWidget.setObjectName("PremadeDrinksWidget")
        PremadeDrinksWidget.resize(632, 382)
        PremadeDrinksWidget.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-image: url(:/images/images/make-drink-icon.svg);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0, stop: 1\n"
"        );\n"
"    }")
        self.premadeDrinkListLabel = QtWidgets.QLabel(PremadeDrinksWidget)
        self.premadeDrinkListLabel.setGeometry(QtCore.QRect(110, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.premadeDrinkListLabel.setFont(font)
        self.premadeDrinkListLabel.setObjectName("premadeDrinkListLabel")
        self.premadeDrinkDetailsLabel = QtWidgets.QLabel(PremadeDrinksWidget)
        self.premadeDrinkDetailsLabel.setGeometry(QtCore.QRect(490, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.premadeDrinkDetailsLabel.setFont(font)
        self.premadeDrinkDetailsLabel.setObjectName("premadeDrinkDetailsLabel")
        self.premadeDrinkDetailsTextBrowser = QtWidgets.QTextBrowser(PremadeDrinksWidget)
        self.premadeDrinkDetailsTextBrowser.setGeometry(QtCore.QRect(410, 50, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.premadeDrinkDetailsTextBrowser.setFont(font)
        self.premadeDrinkDetailsTextBrowser.setObjectName("premadeDrinkDetailsTextBrowser")
        self.premadeDrinkProgressBar = QtWidgets.QProgressBar(PremadeDrinksWidget)
        self.premadeDrinkProgressBar.setEnabled(True)
        self.premadeDrinkProgressBar.setGeometry(QtCore.QRect(10, 310, 611, 23))
        self.premadeDrinkProgressBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.premadeDrinkProgressBar.setProperty("value", 24)
        self.premadeDrinkProgressBar.setObjectName("premadeDrinkProgressBar")
        self.premadeDrinksList = QtWidgets.QListWidget(PremadeDrinksWidget)
        self.premadeDrinksList.setGeometry(QtCore.QRect(10, 50, 371, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.premadeDrinksList.setFont(font)
        self.premadeDrinksList.setObjectName("premadeDrinksList")
        self.strengthLevelGroupBox = QtWidgets.QGroupBox(PremadeDrinksWidget)
        self.strengthLevelGroupBox.setGeometry(QtCore.QRect(10, 180, 611, 91))
        self.strengthLevelGroupBox.setAutoFillBackground(False)
        self.strengthLevelGroupBox.setStyleSheet("QGroupBox{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton{\n"
"font: italic 10pt \"Century Schoolbook\";\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QRadioButton:indicator:unchecked{\n"
"image: url(:/images/images/radio-unchecked.svg);\n"
"}\n"
"\n"
"QRadioButton:indicator:checked{\n"
"image: url(:/images/images/radio-checked.svg);\n"
"}")
        self.strengthLevelGroupBox.setCheckable(False)
        self.strengthLevelGroupBox.setChecked(False)
        self.strengthLevelGroupBox.setObjectName("strengthLevelGroupBox")
        self.fiftyFiftyStrengthLevel = QtWidgets.QRadioButton(self.strengthLevelGroupBox)
        self.fiftyFiftyStrengthLevel.setEnabled(True)
        self.fiftyFiftyStrengthLevel.setGeometry(QtCore.QRect(150, 40, 82, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.fiftyFiftyStrengthLevel.setFont(font)
        self.fiftyFiftyStrengthLevel.setStyleSheet("")
        self.fiftyFiftyStrengthLevel.setObjectName("fiftyFiftyStrengthLevel")
        self.easyTigerStrengthLevel = QtWidgets.QRadioButton(self.strengthLevelGroupBox)
        self.easyTigerStrengthLevel.setEnabled(True)
        self.easyTigerStrengthLevel.setGeometry(QtCore.QRect(20, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.easyTigerStrengthLevel.setFont(font)
        self.easyTigerStrengthLevel.setStyleSheet("")
        self.easyTigerStrengthLevel.setObjectName("easyTigerStrengthLevel")
        self.littyTittyStrengthLevel = QtWidgets.QRadioButton(self.strengthLevelGroupBox)
        self.littyTittyStrengthLevel.setEnabled(True)
        self.littyTittyStrengthLevel.setGeometry(QtCore.QRect(260, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.littyTittyStrengthLevel.setFont(font)
        self.littyTittyStrengthLevel.setStyleSheet("")
        self.littyTittyStrengthLevel.setObjectName("littyTittyStrengthLevel")
        self.adioMfStrengthLevel = QtWidgets.QRadioButton(self.strengthLevelGroupBox)
        self.adioMfStrengthLevel.setEnabled(True)
        self.adioMfStrengthLevel.setGeometry(QtCore.QRect(390, 40, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.adioMfStrengthLevel.setFont(font)
        self.adioMfStrengthLevel.setStyleSheet("")
        self.adioMfStrengthLevel.setObjectName("adioMfStrengthLevel")
        self.makePremadeDrinkButton = QtWidgets.QPushButton(PremadeDrinksWidget)
        self.makePremadeDrinkButton.setGeometry(QtCore.QRect(230, 280, 151, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makePremadeDrinkButton.sizePolicy().hasHeightForWidth())
        self.makePremadeDrinkButton.setSizePolicy(sizePolicy)
        self.makePremadeDrinkButton.setMaximumSize(QtCore.QSize(160000, 160000))
        self.makePremadeDrinkButton.setStyleSheet("")
        self.makePremadeDrinkButton.setText("")
        self.makePremadeDrinkButton.setObjectName("makePremadeDrinkButton")

        self.retranslateUi(PremadeDrinksWidget)
        QtCore.QMetaObject.connectSlotsByName(PremadeDrinksWidget)

    def retranslateUi(self, PremadeDrinksWidget):
        _translate = QtCore.QCoreApplication.translate
        PremadeDrinksWidget.setWindowTitle(_translate("PremadeDrinksWidget", "Premade Drinks"))
        self.premadeDrinkListLabel.setText(_translate("PremadeDrinksWidget", "Available Drinks to Make"))
        self.premadeDrinkDetailsLabel.setText(_translate("PremadeDrinksWidget", "Drink Details"))
        self.strengthLevelGroupBox.setTitle(_translate("PremadeDrinksWidget", "Strength Level"))
        self.fiftyFiftyStrengthLevel.setText(_translate("PremadeDrinksWidget", "50/50"))
        self.easyTigerStrengthLevel.setText(_translate("PremadeDrinksWidget", "Easy Tiger"))
        self.littyTittyStrengthLevel.setText(_translate("PremadeDrinksWidget", "Litty Titty"))
        self.adioMfStrengthLevel.setText(_translate("PremadeDrinksWidget", "ADIOS MUTHAFUCKA!"))
from . import premadeDrinksWidgetResource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PremadeDrinksWidget = QtWidgets.QWidget()
    ui = Ui_PremadeDrinksWidget()
    ui.setupUi(PremadeDrinksWidget)
    PremadeDrinksWidget.show()
    sys.exit(app.exec_())
