# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ui_files/spotify.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpotifyWidget(object):
    def setupUi(self, SpotifyWidget):
        SpotifyWidget.setObjectName("SpotifyWidget")
        SpotifyWidget.resize(635, 368)
        SpotifyWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.spotifyTabWidget = QtWidgets.QTabWidget(SpotifyWidget)
        self.spotifyTabWidget.setGeometry(QtCore.QRect(10, 10, 611, 241))
        self.spotifyTabWidget.setStyleSheet("QListWidget{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QLineEdit{\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTabWidget{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QTabBar{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.spotifyTabWidget.setObjectName("spotifyTabWidget")
        self.spotifySearchTab = QtWidgets.QWidget()
        self.spotifySearchTab.setObjectName("spotifySearchTab")
        self.spotifySearchInputField = QtWidgets.QLineEdit(self.spotifySearchTab)
        self.spotifySearchInputField.setGeometry(QtCore.QRect(10, 10, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.spotifySearchInputField.setFont(font)
        self.spotifySearchInputField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.spotifySearchInputField.setObjectName("spotifySearchInputField")
        self.spotifySearchResultsField = QtWidgets.QListWidget(self.spotifySearchTab)
        self.spotifySearchResultsField.setGeometry(QtCore.QRect(10, 40, 581, 161))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.spotifySearchResultsField.setFont(font)
        self.spotifySearchResultsField.setStyleSheet("color: rgb(255, 255, 255);")
        self.spotifySearchResultsField.setObjectName("spotifySearchResultsField")
        self.spotifySearchButton = QtWidgets.QPushButton(self.spotifySearchTab)
        self.spotifySearchButton.setGeometry(QtCore.QRect(470, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.spotifySearchButton.setFont(font)
        self.spotifySearchButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.spotifySearchButton.setObjectName("spotifySearchButton")
        self.spotifyTabWidget.addTab(self.spotifySearchTab, "")
        self.spotifyQueueTab = QtWidgets.QWidget()
        self.spotifyQueueTab.setObjectName("spotifyQueueTab")
        self.spotifyQueueField = QtWidgets.QListWidget(self.spotifyQueueTab)
        self.spotifyQueueField.setGeometry(QtCore.QRect(10, 10, 581, 211))
        self.spotifyQueueField.setObjectName("spotifyQueueField")
        self.spotifyTabWidget.addTab(self.spotifyQueueTab, "")
        self.spotifyPlayPauseButton = QtWidgets.QPushButton(SpotifyWidget)
        self.spotifyPlayPauseButton.setGeometry(QtCore.QRect(290, 260, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.spotifyPlayPauseButton.setFont(font)
        self.spotifyPlayPauseButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/images/images/play-button.png);\n"
"border-radius:50px;\n"
"max-width:50px;\n"
"max-height:50px;\n"
"min-width:48px;\n"
"min-height:48px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0, stop: 1\n"
"        );\n"
"    }")
        self.spotifyPlayPauseButton.setText("")
        self.spotifyPlayPauseButton.setObjectName("spotifyPlayPauseButton")
        self.spotifyNextButton = QtWidgets.QPushButton(SpotifyWidget)
        self.spotifyNextButton.setGeometry(QtCore.QRect(430, 260, 50, 48))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.spotifyNextButton.setFont(font)
        self.spotifyNextButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/images/images/next-button.png);\n"
"border-radius:50px;\n"
"max-width:50px;\n"
"max-height:50px;\n"
"min-width:48px;\n"
"min-height:48px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0, stop: 1\n"
"        );\n"
"    }")
        self.spotifyNextButton.setText("")
        self.spotifyNextButton.setObjectName("spotifyNextButton")
        self.spotifyPreviousButton = QtWidgets.QPushButton(SpotifyWidget)
        self.spotifyPreviousButton.setGeometry(QtCore.QRect(150, 260, 50, 48))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.spotifyPreviousButton.setFont(font)
        self.spotifyPreviousButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/images/images/previous-button.png);\n"
"border-radius:50px;\n"
"max-width:50px;\n"
"max-height:50px;\n"
"min-width:48px;\n"
"min-height:48px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0, stop: 1\n"
"        );\n"
"    }")
        self.spotifyPreviousButton.setText("")
        self.spotifyPreviousButton.setObjectName("spotifyPreviousButton")
        self.currentlyPlayingLabel = QtWidgets.QLabel(SpotifyWidget)
        self.currentlyPlayingLabel.setGeometry(QtCore.QRect(150, 350, 331, 20))
        self.currentlyPlayingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentlyPlayingLabel.setObjectName("currentlyPlayingLabel")
        self.currentlyPlayingLabel_2 = QtWidgets.QLabel(SpotifyWidget)
        self.currentlyPlayingLabel_2.setGeometry(QtCore.QRect(260, 330, 101, 20))
        self.currentlyPlayingLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.currentlyPlayingLabel_2.setObjectName("currentlyPlayingLabel_2")

        self.retranslateUi(SpotifyWidget)
        self.spotifyTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SpotifyWidget)

    def retranslateUi(self, SpotifyWidget):
        _translate = QtCore.QCoreApplication.translate
        SpotifyWidget.setWindowTitle(_translate("SpotifyWidget", "Spotify"))
        self.spotifySearchInputField.setPlaceholderText(_translate("SpotifyWidget", "Search for songs, artist, etc..."))
        self.spotifySearchButton.setText(_translate("SpotifyWidget", "Search"))
        self.spotifyTabWidget.setTabText(self.spotifyTabWidget.indexOf(self.spotifySearchTab), _translate("SpotifyWidget", "Search"))
        self.spotifyTabWidget.setTabToolTip(self.spotifyTabWidget.indexOf(self.spotifySearchTab), _translate("SpotifyWidget", "Search for songs, artists, playlist, etc..."))
        self.spotifyTabWidget.setTabText(self.spotifyTabWidget.indexOf(self.spotifyQueueTab), _translate("SpotifyWidget", "Queue"))
        self.spotifyTabWidget.setTabToolTip(self.spotifyTabWidget.indexOf(self.spotifyQueueTab), _translate("SpotifyWidget", "View current queue"))
        self.currentlyPlayingLabel.setText(_translate("SpotifyWidget", "TextLabel"))
        self.currentlyPlayingLabel_2.setText(_translate("SpotifyWidget", "Now Playing"))
from . import spotifyWidgetResource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpotifyWidget = QtWidgets.QWidget()
    ui = Ui_SpotifyWidget()
    ui.setupUi(SpotifyWidget)
    SpotifyWidget.show()
    sys.exit(app.exec_())
